# Generated by Django 5.0.3 on 2024-03-24 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='cart',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.cart'),
        ),
    ]
